version: '3.8'

services:
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - ".:/myapp"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
